services:
  - type: web
    name: school-data-dash
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dash_app:server -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
